<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LVP1210002" name="com.lohika.atf.tests.TestF" tests="10" failures="0" timestamp="15 Oct 2014 12:51:24 GMT" time="32.718" errors="1">
  <testcase name="addProducts" time="4.358" classname="com.lohika.atf.tests.TestF"/>
  <testcase name="CSVaddProducts" time="3.849" classname="com.lohika.atf.tests.TestF"/>
  <testcase name="editProductSingleRow" time="0.001" classname="com.lohika.atf.tests.TestF"/>
  <testcase name="calcPrice" time="0.146" classname="com.lohika.atf.tests.TestF">
    <error type="java.lang.AssertionError" message="expected [43.849999999999994] but found [-3.849999999999998]">
      <![CDATA[java.lang.AssertionError: expected [43.849999999999994] but found [-3.849999999999998]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.lohika.atf.tests.TestF.calcPrice(TestF.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- calcPrice -->
  <testcase name="CSVaddProducts" time="3.555" classname="com.lohika.atf.tests.TestF"/>
  <testcase name="editCancelProduct" time="1.410" classname="com.lohika.atf.tests.TestF"/>
  <testcase name="editProductInvoice" time="0.781" classname="com.lohika.atf.tests.TestF"/>
  <testcase name="validationEditProductFields" time="6.768" classname="com.lohika.atf.tests.TestF"/>
  <testcase name="deleteProducts" time="0.152" classname="com.lohika.atf.tests.TestF"/>
  <testcase name="validationAddProductFields" time="11.698" classname="com.lohika.atf.tests.TestF"/>
</testsuite> <!-- com.lohika.atf.tests.TestF -->
